name: Supplementary
description: Non-functional requirements (NFRs)
labels: ["type: nfr"]
body:
  - type: input
    attributes:
      label: Requirement Name
      placeholder: Enter NFR title
  - type: textarea
    attributes:
      label: Description
      description: Detailed description of the non-functional requirement
  - type: dropdown
    attributes:
      label: Category
      options:
        - Performance
        - Security
        - Usability
        - Reliability
        - Legal
        - Maintainability
        - Portability
  - type: dropdown
    attributes:
      label: Priority
      options:
        - High
        - Medium
        - Low
  - type: input
    attributes:
      label: Derived from
      placeholder: Feature #01
